fn error_me(throw: bool) -> Result<(), usize> {

}

func main() -> Result<(), usize> {
    let value: ()

}

